language: c
script: asdf plugin-test skaffold https://github.com/kristoflemmens/asdf-skaffold.git
before_script:
  - git clone https://github.com/asdf-vm/asdf.git
  - . asdf/asdf.sh
os:
  - linux
  - osx
